Update API health check and clear connection strings in appsettings

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -73,15 +73,30 @@ jobs:
       - name: Wait for API to Start
         run: |
           for i in {1..10}; do
+            echo "Tentando acessar endpoint de health..."
+            curl -v http://localhost:5010/auth/health || true
             if curl -f http://localhost:5010/auth/health > /dev/null 2>&1; then
               echo "API started successfully"
               exit 0
-            fi
-            echo "Waiting for API to start... Attempt $i of 10"
-            sleep 3
-          done
-          echo "API failed to start"
-          exit 1
+              fi
+              echo "Waiting for API to start... Attempt $i of 10"
+              sleep 3
+            done
+            echo "API failed to start"
+            exit 1
+
+      # - name: Wait for API to Start
+      #   run: |
+      #     for i in {1..10}; do
+      #       if curl -f http://localhost:5010/auth/health > /dev/null 2>&1; then
+      #         echo "API started successfully"
+      #         exit 0
+      #       fi
+      #       echo "Waiting for API to start... Attempt $i of 10"
+      #       sleep 3
+      #     done
+      #     echo "API failed to start"
+      #     exit 1
 
       - name: Test API Health
         run: curl -f http://localhost:5010/criar/contato/health || exit 1
